### ISSUE TITLE
dict_generic has minimum length 1

### ISSUE THREAD

**Issue by aherrmann** [mooreryan/gleam_qcheck#3]
First of all thank you for creating this library!

While using this library I noticed that `dict_generic` generates dictionaries with [a minimum length of 1](https://github.com/mooreryan/gleam_qcheck/blob/7ce8170570f54d8f32fcf6b4ff97add9b894a8af/src/qcheck/generator.gleam#L829). This is in contrast to [`set_generic`](https://github.com/mooreryan/gleam_qcheck/blob/7ce8170570f54d8f32fcf6b4ff97add9b894a8af/src/qcheck/generator.gleam#L811) which generates sets at a minimum size of zero.

I ran into this in a use-case where the maximum dictionary size I want to generate depends on another generator and can go down to zero, which triggers a failure due to [this assertion](https://github.com/mooreryan/gleam_qcheck/blob/7ce8170570f54d8f32fcf6b4ff97add9b894a8af/src/qcheck/generator.gleam#L335).

Was there any particular reason to choose a minimum size of 1 for dictionary generation? If not it may be better to allow a minimum size of zero.

**Comment by mooreryan** [comment]
Thanks for opening this issue.  

I believe that it is likely a mistake on my part that the minimum size of generated dictionaries is 1 as compared to min size of sets, which is 0.  The stdlib's set is even implemented in terms of the dict, so I can't think of any reason that I would have done that intentionally.  I also went back to some of the libraries that this one is based on and don't see any special restrictions that generated dicts (or maps, hash tables, etc.) should be `>= 1`.

Anyway, I think you're right in that it would be more correct to allow generation of empty dicts.
