### ISSUE TITLE
Recommended way to use 2 generators at once

### ISSUE THREAD

**Issue by lpil** [mooreryan/gleam_qcheck#6]
Hello! Thank you for this library, is had found a bunch of bugs for me!

I've got this code currently

```gleam
  use #(x, y) <- qcheck.given(qcheck.map2(
    fn(x, y) { #(x, y) },
    qcheck.int_uniform(),
    qcheck.int_uniform(),
  ))
```

It works, but I was surprised by how verbose it was, and was unsure if I was doing the right thing, especially as it got a fair bit "uglier" with 3 or 4 values.

Is this the right way to do this?

Thanks,
Louis

**Comment by mooreryan** [comment]
Hey, I think the nicest way would probably depend on what you were trying to do.  

If you need multiple values and you just need a tuple you can use the [tupleN](https://hexdocs.pm/qcheck/qcheck.html#tuple2) functions like:

```gleam
pub fn example__test() {
  use #(x, y) <- qcheck.given(qcheck.tuple2(
    qcheck.int_uniform_inclusive(1, 10),
    qcheck.int_uniform_inclusive(11, 20),
  ))
  x != y
}
```

If you wanted to do something more in-depth with the values, you could use `mapN` functions, something like:

```gleam
type Point {
  Point(Int, Int)
}

fn point_generator() {
  use x, y <- qcheck.map2(g1: qcheck.int_uniform(), g2: qcheck.int_uniform())
  Point(x, y)
}
```

If you need values that depend on a previous random value, you can use `bind`.

If you have something very complicated or you need a ton of generated values that are independent of each other, you could try [this style](https://github.com/mooreryan/gleam_qcheck?tab=readme-ov-file#applicative-sytle) if that is to your liking.

Let me know if that clears it up! (I know the API docs don't have too many examples yet.  I have been meaning to clean up some of the api...eg `map` takes the function last but the `mapN` takes the function first, and that hides the fact that you can use the `use` syntax with it.)

**Comment by lpil** [comment]
Thank you!
